#!/usr/bin/env zsh
cd $HOME/.vim/config
sed -i .bak 's/<esc>/<ESC>/' *.vim
sed -i .bak 's/<cr>/<CR>/' *.vim
sed -i .bak 's/no /noremap /' *.vim
rm *.bak
cd $HOME/.vim/config/extensions
sed -i .bak 's/<esc>/<ESC>/' *.vim
sed -i .bak 's/no /noremap /' *.vim
sed -i .bak 's/<cr>/<CR>/' *.vim
rm *.bak
