source ~/.vim/config/extensions/vundle.vim
source ~/.vim/config/extensions/snippets.vim
source ~/.vim/config/extensions/autocomplete.vim
source ~/.vim/config/defaults.vim
source ~/.vim/config/abbr.vim
source ~/.vim/config/functions.vim
source ~/.vim/config/autocmds.vim
source ~/.vim/config/escape.vim
source ~/.vim/config/motions.vim
source ~/.vim/config/saving.vim
source ~/.vim/config/folding.vim
source ~/.vim/config/mappings.vim
source ~/.vim/config/splits.vim
source ~/.vim/config/reg.vim
