#!/bin/sh

set -e

if tmux has-session -t dots 2> /dev/null; then
  tmux switch-client -t dots
  exit
fi

tmux new-session -d -s dots -n vim

tmux send-keys -t dots:vim "vimrc" Enter
tmux new-window -t dots -c "$HOME/.zprezto/runcoms/" -n shellrc
tmux send-keys -t dots:shellrc "vim ." Enter
tmux new-window -t dots -c "$HOME/.zprezto/modules/zsh-aliases/" -n aliases
tmux send-keys -t dots:aliases "vim ." Enter
tmux switch-client -t dots:vim.left
