#!/bin/sh

set -e

if tmux has-session -t dots 2> /dev/null; then
  $HOME/bin/switch_or_attach dots
  exit
fi

tmux new-session -d -s dots -n vim

tmux send-keys -t dots:vim "vim  .vim/" Enter
tmux new-window -t dots -c "$HOME/.zprezto/runcoms/" -n shellrc
tmux send-keys -t dots:shellrc "vim ." Enter
tmux new-window -t dots -c "$HOME/.zprezto/modules/zsh-aliases/" -n aliases
tmux send-keys -t dots:aliases "vim ." Enter
$HOME/bin/switch_or_attach dots:vim.left
