#!/bin/sh

set -e

if tmux has-session -t wp 2> /dev/null; then
  $HOME/bin/switch_or_attach wp
  exit
fi

tmux new-session -c "$HOME/Sites/wp-content/themes" -d -s wp -n theme
tmux send-keys -t wp:theme "vim ." Enter

tmux new-window -t wp -c "$HOME/Sites/wp-content/plugins/" -n plugins
tmux send-keys -t wp:plugins "vim ." Enter

tmux new-window -t wp -c "$HOME/Sites" -n shell
tmux send-keys -t wp:shell "server-up" Enter
$HOME/bin/switch_or_attach wp:shell.left
